"""empty message

Revision ID: 19c2d5ef1bb8
Revises: 9f5228dae77c
Create Date: 2020-09-27 18:53:41.652523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c2d5ef1bb8'
down_revision = '9f5228dae77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DatasetManager', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DatasetManager', 'comment')
    # ### end Alembic commands ###
