"""empty message

Revision ID: 845a87397576
Revises: 8976b8165527
Create Date: 2020-10-09 13:07:34.485368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845a87397576'
down_revision = '8976b8165527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WebContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webpageName', sa.String(length=255), nullable=False),
    sa.Column('blockName', sa.String(length=255), nullable=True),
    sa.Column('webContent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_WebContent'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebContent')
    # ### end Alembic commands ###
